import fs from 'node:fs';import path from 'node:path';
import {site,pages,target,siteUrl,basePath} from './config.mjs';
const root=process.cwd();
const imgs=fs.readdirSync(path.join(root,'public/images')).filter(x=>x.endsWith('.webp')&&x!=='logo.webp');
const B=basePath;const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const link=(slug,label)=>`<a href="${B}${slug?slug+'/':''}">${label}</a>`;
const nav=`<header class="site-header"><div class="wrap nav"><a class="brand" href="${B}"><img src="${B}images/logo.webp" alt="Global Investment Yapı Geliştirme logosu"><span>GLOBAL INVESTMENT<small>YAPI GELİŞTİRME A.Ş.</small></span></a><nav class="menu">${link('tiny-house-modelleri','Modeller')}${link('projeler','Projeler')}${link('ic-mekanlar','İç Mekân')}${link('hakkimizda','Hakkımızda')}${link('tiny-house-rehberi','Rehber')}</nav><a class="btn primary" href="${B}iletisim-teklif/">Teklif Al</a></div></header>`;
const footer=`<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div><h3>${site.brand}</h3><p>Modern, fonksiyonel ve sürdürülebilir tiny house çözümleri.</p></div><div><h4>Hızlı Linkler</h4><p>${link('tiny-house-modelleri','Modeller')}<br>${link('galeri','Galeri')}<br>${link('sik-sorulan-sorular','S.S.S.')}</p></div><div><h4>İletişim</h4><p>${site.phone}<br>${site.email}</p></div></div><div class="copyright">© ${new Date().getFullYear()} Global Investment Yapı Geliştirme A.Ş.</div></div></footer>`;
const features=`<div class="wrap featurebar"><div class="feature"><b>Özel Tasarım</b><span>İhtiyaca göre planlama</span></div><div class="feature"><b>Taşınabilir</b><span>Esnek kullanım senaryoları</span></div><div class="feature"><b>Kaliteli Üretim</b><span>Dayanıklı malzeme ve işçilik</span></div><div class="feature"><b>Anahtar Teslim</b><span>Tek noktadan süreç yönetimi</span></div></div>`;
const modelSlugs=['a-frame-tiny-house','loft-tiny-house','kompakt-tiny-house','aile-tipi-tiny-house','tekerlekli-tiny-house','ozel-tasarim-tiny-house'];
const modelPages=pages.filter(p=>modelSlugs.includes(p.slug));
const models=()=>`<div class="cards">${modelPages.map((m,i)=>`<a class="card" href="${B}${m.slug}/"><img loading="lazy" src="${B}images/${m.hero}" alt="${esc(m.title)}"><div class="card-body"><h3>${m.title}</h3><p>${m.body}</p></div></a>`).join('')}</div>`;
const gallery=(count=12,offset=0)=>`<div class="gallery">${Array.from({length:count},(_,i)=>{const im=imgs[(i+offset)%imgs.length];return `<figure><img loading="lazy" src="${B}images/${im}" alt="Global Investment tiny house proje ve iç mekân görseli ${i+1}"></figure>`}).join('')}</div>`;
const faq=`<div class="faq"><details open><summary>Tiny house ölçüleri nasıl belirlenir?</summary><p>Model, kullanım amacı, şasi yapısı ve iç mekân beklentilerine göre ölçülendirme yapılır.</p></details><details><summary>İç mekân kişiselleştirilebilir mi?</summary><p>Mutfak, dolap, kaplama, renk ve depolama detayları projeye göre özelleştirilebilir.</p></details><details><summary>Üretim süresi ne kadar?</summary><p>Süre model, ekipman ve özel üretim kapsamına göre teklif aşamasında netleştirilir.</p></details><details><summary>Teslimat nasıl yapılır?</summary><p>Teslimat planı ürün ölçüsü ve hedef konuma göre hazırlanır.</p></details></div>`;
// Netlify'da form gonderimi Netlify Forms'a duser; diger hedeflerde arayuz demo olarak calisir.
const netlifyForm=target==='netlify';
const formFields=`<label>Ad Soyad<input required name="name"></label><label>Telefon<input required name="phone"></label><label>İlgilendiğiniz model<select name="model"><option>A-Frame</option><option>Loft</option><option>Kompakt</option><option>Aile Tipi</option><option>Özel Tasarım</option></select></label><label>Mesaj<textarea name="message"></textarea></label><button class="btn primary" type="submit">Teklif Talebi Gönder</button>`;
const form=netlifyForm
  ?`<form class="form" name="teklif" method="POST" action="${B}tesekkurler/" data-netlify="true" netlify-honeypot="bot-field"><input type="hidden" name="form-name" value="teklif"><p class="hp"><label>Bu alanı boş bırakın<input name="bot-field"></label></p>${formFields}</form>`
  :`<form class="form" onsubmit="event.preventDefault();alert('Form arayüzü hazır. Gerçek gönderim için e-posta/Formspree entegrasyonu eklenebilir.')">${formFields}</form>`;
function body(p){if(p.kind==='home')return `${features}<section><div class="wrap"><div class="section-head"><div><span class="eyebrow">KOLEKSİYON</span><h2>Yaşam tarzınıza uygun model</h2></div><p>A-frame’den kompakt çözümlere, farklı plan ve cephe seçenekleri.</p></div>${models()}</div></section><section><div class="wrap"><div class="section-head"><div><span class="eyebrow">GERÇEK PROJELER</span><h2>İçeriden dışarıya gerçek yaşam</h2></div></div>${gallery(8,2)}</div></section><section><div class="wrap band"><span class="eyebrow">NASIL ÇALIŞIYORUZ?</span><h2>5 adımda üretim süreci</h2><div class="steps">${['İhtiyaç Analizi','Tasarım','Üretim','Kalite Kontrol','Anahtar Teslim'].map((x,i)=>`<div class="step"><strong>0${i+1}</strong><b>${x}</b></div>`).join('')}</div></div></section><section><div class="wrap cta"><div><span class="eyebrow">PROJENİZİ KONUŞALIM</span><h2>Size uygun tiny house’u birlikte tasarlayalım.</h2></div><a class="btn" href="${B}iletisim-teklif/">Teklif Al</a></div></section>`;
if(p.kind==='models')return `<section><div class="wrap">${models()}</div></section>`;
if(p.kind==='gallery'||p.kind==='projects')return `<section><div class="wrap">${gallery(18,p.kind==='projects'?4:0)}</div></section>`;
if(p.kind==='process')return `<section><div class="wrap band"><div class="steps">${['İhtiyaç Analizi','Tasarım & Planlama','Üretim','Kalite Kontrol','Teslimat'].map((x,i)=>`<div class="step"><strong>0${i+1}</strong><b>${x}</b><p>${['Beklenti ve kullanım senaryosunu netleştiririz.','Plan, malzeme ve cephe kararlarını veririz.','Üretimi kontrollü şekilde yürütürüz.','Elektrik, tesisat ve detay kontrollerini yaparız.','Planlanan lokasyona teslim organizasyonunu tamamlarız.'][i]}</p></div>`).join('')}</div></div></section>`;
if(p.kind==='faq')return `<section><div class="wrap">${faq}</div></section>`;
if(p.kind==='contact')return `<section><div class="wrap contact-grid"><div class="prose"><h2>Projenizi anlatın</h2><p>Model, ölçü, kullanım amacı ve teslimat bölgesini paylaşın. Size uygun çözümü birlikte netleştirelim.</p><p><b>Telefon:</b> ${site.phone}<br><b>E-posta:</b> ${site.email}</p></div>${form}</div></section>`;
if(p.kind==='technical')return `<section><div class="wrap content-grid"><div class="prose"><h2>Teknik yapı</h2><p>Teknik değerler model ve proje kapsamına göre sözleşmede netleştirilir. Aşağıdaki başlıklar standart teknik dosyanın temelini oluşturur.</p></div><div class="specs">${['Şasi & Konstrüksiyon','Isı Yalıtımı','Dış Cephe','Elektrik','Temiz / Atık Su','Doğrama & Cam'].map(x=>`<div class="spec"><b>${x}</b><span>Projeye göre seçilebilir teknik seçenekler</span></div>`).join('')}</div></div></section>`;
if(p.kind==='blog')return `<section><div class="wrap cards">${['Tiny house seçerken nelere dikkat edilmeli?','Loft planın avantajları','Küçük alanda depolama fikirleri','Tiny house iç mekân planlama','Cephe malzemesi seçimi','Teslimat öncesi kontrol listesi'].map((x,i)=>`<article class="card"><img src="${B}images/${imgs[(i+8)%imgs.length]}" alt="${x}"><div class="card-body"><h3>${x}</h3><p>Karar sürecini kolaylaştıran kısa rehber içeriği.</p></div></article>`).join('')}</div></section>`;
return `<section><div class="wrap content-grid"><div class="prose"><h2>${p.title}</h2><p>${p.body}</p><p>Global Investment Yapı Geliştirme, gerçek proje deneyimini modern planlama ve sade malzeme diliyle birleştirir.</p><a class="btn primary" href="${B}iletisim-teklif/">Teklif Al</a></div><div>${gallery(4,modelSlugs.indexOf(p.slug)+5)}</div></div></section>`;}
function page(p){const canonical=`${siteUrl}/${p.slug?`${p.slug}/`:''}`;return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.seo)}</title><meta name="description" content="${esc(p.desc)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(p.seo)}"><meta property="og:description" content="${esc(p.desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta property="og:image" content="${siteUrl}/images/${p.hero}"><link rel="icon" href="${B}images/logo.webp" type="image/webp"><link rel="stylesheet" href="${B}styles.css"><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@type":"WebPage",name:p.title,description:p.desc,url:canonical,inLanguage:'tr-TR'})}</script></head><body>${nav}<main><section class="hero"><div class="wrap hero-grid"><div class="hero-copy"><span class="eyebrow">${p.eyebrow}</span><h1>${p.title}</h1><p>${p.body}</p><div class="actions"><a class="btn primary" href="${B}tiny-house-modelleri/">Modelleri İncele</a><a class="btn" href="${B}iletisim-teklif/">Teklif Al</a></div></div><div class="hero-media"><img src="${B}images/${p.hero}" alt="${esc(p.title)}"></div></div></section>${body(p)}</main>${footer}</body></html>`}
// Sitemap disi yardimci sayfalar (404, form tesekkur) - arama motorlarina kapali.
function utilityPage(title,text,actionLabel){return `<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ${esc(site.shortBrand)}</title><meta name="robots" content="noindex"><link rel="icon" href="${B}images/logo.webp" type="image/webp"><link rel="stylesheet" href="${B}styles.css"></head><body>${nav}<main><section class="hero"><div class="wrap"><div class="prose"><span class="eyebrow">${esc(site.shortBrand)}</span><h1>${esc(title)}</h1><p>${esc(text)}</p><a class="btn primary" href="${B}">${esc(actionLabel)}</a></div></div></section></main>${footer}</body></html>`}

const dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});fs.cpSync(path.join(root,'public'),dist,{recursive:true});fs.copyFileSync(path.join(root,'src/styles.css'),path.join(dist,'styles.css'));
for(const p of pages){const d=path.join(dist,p.slug);fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),page(p));}
// Netlify ve GitHub Pages ikisi de yayin kokundeki 404.html'i otomatik kullanir.
fs.writeFileSync(path.join(dist,'404.html'),utilityPage('Sayfa bulunamadı','Aradığınız sayfa taşınmış veya kaldırılmış olabilir.','Ana sayfaya dön'));
if(netlifyForm){const d=path.join(dist,'tesekkurler');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,'index.html'),utilityPage('Teklif talebiniz alındı','En kısa sürede sizinle iletişime geçeceğiz.','Ana sayfaya dön'));}
const urls=pages.map(p=>`${siteUrl}/${p.slug?`${p.slug}/`:''}`);fs.writeFileSync(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${u}</loc></url>`).join('')}</urlset>`);fs.writeFileSync(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`);console.log(`Built ${pages.length} pages | target=${target} | base=${B} | url=${siteUrl}`);
